#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libwpd
Version  : 0.10.3
Release  : 2
URL      : https://dev-www.libreoffice.org/src/libwpd-0.10.3.tar.xz
Source0  : https://dev-www.libreoffice.org/src/libwpd-0.10.3.tar.xz
Summary  : A library for reading and writing Corel WordPerfect(tm) documents
Group    : Development/Tools
License  : LGPL-2.1 MPL-2.0-no-copyleft-exception
Requires: libwpd-bin
Requires: libwpd-lib
Requires: libwpd-license
BuildRequires : boost-dev
BuildRequires : doxygen
BuildRequires : pkgconfig(librevenge-0.0)
BuildRequires : pkgconfig(librevenge-generators-0.0)

%description
libwpd is a library for import of WordPerfect documents. It is used by,
for example, AbiWord and LibreOffice.

%package bin
Summary: bin components for the libwpd package.
Group: Binaries
Requires: libwpd-license

%description bin
bin components for the libwpd package.


%package dev
Summary: dev components for the libwpd package.
Group: Development
Requires: libwpd-lib
Requires: libwpd-bin
Provides: libwpd-devel

%description dev
dev components for the libwpd package.


%package doc
Summary: doc components for the libwpd package.
Group: Documentation

%description doc
doc components for the libwpd package.


%package lib
Summary: lib components for the libwpd package.
Group: Libraries
Requires: libwpd-license

%description lib
lib components for the libwpd package.


%package license
Summary: license components for the libwpd package.
Group: Default

%description license
license components for the libwpd package.


%prep
%setup -q -n libwpd-0.10.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534633633
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1534633633
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libwpd
cp COPYING.LGPL %{buildroot}/usr/share/doc/libwpd/COPYING.LGPL
cp COPYING.MPL %{buildroot}/usr/share/doc/libwpd/COPYING.MPL
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/wpd2html
/usr/bin/wpd2raw
/usr/bin/wpd2text

%files dev
%defattr(-,root,root,-)
/usr/include/libwpd-0.10/libwpd/WPDocument.h
/usr/include/libwpd-0.10/libwpd/libwpd.h
/usr/lib64/libwpd-0.10.so
/usr/lib64/pkgconfig/libwpd-0.10.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libwpd/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libwpd-0.10.so.10
/usr/lib64/libwpd-0.10.so.10.0.3

%files license
%defattr(-,root,root,-)
/usr/share/doc/libwpd/COPYING.LGPL
/usr/share/doc/libwpd/COPYING.MPL
